### ISSUE TITLE
isGeometryOf property to describe what resources use a geometry

### ISSUE THREAD

**Issue by benjaminleighton** [CSIRO-enviro-informatics/geosparql-ext-ont#5]
A property to allow navigation from a geometry to things that use that geometry likely geox:isGeometryOf owl:inverseOf geo:hasGeometry as suggested at https://github.com/CSIRO-enviro-informatics/geometry-data-service/issues/8

**Comment by dr-shorthair** [comment]
https://github.com/CSIRO-enviro-informatics/geosparql-ext-ont/blob/master/geox.ttl#L243
