### ISSUE TITLE
Geometry encoding as DGGS cells

### ISSUE THREAD

**Issue by dr-shorthair** [CSIRO-enviro-informatics/geosparql-ext-ont#7]
DGGS offers an alternative representation of geography, as a set of cells, potentially of various scales. 
In order to make this useable in the context of GeoSPARQL, while retaining the compact representation, a direct representation in DGGS is required.

**Comment by dr-shorthair** [comment]
The proposal was originated by @nicholascar in https://github.com/GeoscienceAustralia/AusPIX-DGGS-ontology/issues/1 and then I (mistakenly) caused it to be elaborated here: https://github.com/GeoscienceAustralia/Place-Names/issues/21 

In order to keep the threads clean, I've copied an editted version of the conversations here:


**@nicholascar commented 3 hours ago**
Actually it should be:
```Turtle
<x> a geo:Feature ;
    geo:hasGeometry "SPECIAL-DGGS-GEOMETRY"^^geox:dggsLiteral ;
.
```
where SPECIAL-DGGS-GEOMETRY is a string of integers, as per the DGGS addressing.

So not aop:Cell has a SPECIAL-DGGS-GEOMETRY but a standard geo:Feature.

**@dr-shorthair commented 2 hours ago •** 
[...] This is more direct
```Turtle
:F987 a geo:Feature ;
   geo:hasGeometry [
        a geo:Geometry ;
        geox:asDGGS "R7828 R78520 R78521 R78522 R78523"^^geox:dggsLiteral ;
     ] ;
.
```
(geo:hasGeometry is an owl:ObjectProperty so it must contain a blank-node or URI-reference. )

**@bellie888 commented 2 hours ago**
@dr-shorthair @nicholascar
We often make a visualisation of DGGS cells to include on GIS maps. In a sense this is "usable geometry".
Note though, representing spatial data as DGGS cells has a lossy component to it and the data will have a rasterised look to it. For example, a point that has been converted to a cell, that point could be anywhere in the cell (not just the centre). In a level 10 cell it could be anywhere in a 169 X 169 metre box.

To minimise this "lossy" component, we can use a higher resolution cell. In fact, the cell size could be smaller that the accuracy of the original spatial data.

An advantage of AusPIX is that the high resolution cells are always within their lower resolution parent. For example R574278 is somewhere inside R574

For any cell we can ask what the "useable geometry" is - centroid, verticies etc
http://ec2-52-63-73-113.ap-southeast-2.compute.amazonaws.com/AusPIX-DGGS-dataset/ausPIX/S704884126

**@dr-shorthair commented 2 hours ago**
The 'lossiness' is implicit in geox:asDGGS.
(not really 'lossiness' - rather just fixed precision.)

**@bellie888 commented 36 minutes ago**
Yep, true
Here is an example of a DGGS'ed stream.

![82781143-6aac8780-9e9c-11ea-88fa-825da1d119f1](https://user-images.githubusercontent.com/608303/82784214-66d03380-9ea3-11ea-815f-c149e7051d07.jpg)

**@nicholascar commented 28 minutes ago**
So this is why I think using literals for the DGGS data is a good idea: the structure of the numbers - R574278 being within R574 - means that secondary systems processing literals like that will be fast.

**@dr-shorthair commented 9 minutes ago**
@bellie888 the idea is that the dggsLiteral would take a list of Cell IDs. e.g.
```Turtle
ex:XX_10532
  rdf:type :Place ;
  :hasPlaceClassification <http://pid.geoscience.gov.au/def/voc/ga/PlaceType/WATERCOURSE> ;
  dcterms:identifier "XX_10532" ;
  geo:hasGeometry [
     rdf:type geo:Geometry ;
     geox:asDGGS "R7430550 R7430551 R7430552 ... "^^geox:dggsLiteral ;
    ] ;
  geo:hasGeometry [
      rdf:type sf:LineString ;
      geo:asWKT "LINESTRING(-25.3415 131.0354 , ... )"^^geo:wktLiteral ;
    ] ;
.
```
**@bellie888 commented 5 minutes ago**
nice, is there a limit?

**@dr-shorthair commented now**
We are making this up, so there is only a limit if you want one.

**Comment by dr-shorthair** [comment]
Is the encoding of DGGS cells in the form 'R7430550' unique and standardized? 
@bellie888 ?

**Comment by dr-shorthair** [comment]
i.e. do all DGGS cell identifiers match the regex ([N-S][0-8]+) ?

**Comment by jyucsiro** [comment]
@dr-shorthair that appears to be the case. See 
https://github.com/GeoscienceAustralia/AusPIX_DGGS/blob/master/auspixdggs/auspixengine/dggs.py#L185

And there are 9 cells nested for each parent cell.

**Comment by nicholascar** [comment]
Can you refine that regex `([N-S][0-8]+)` into perhaps `([N-S])([0-8]{1})([0-8]{2})([0-8]{2, 7})` or similar so that the structure of the ID can be broken into `$1`, `$2`, `$3` etc. and thus the parts pulled out more easily.

**Comment by dr-shorthair** [comment]
Yes, 9 nested cells, numbered 0-8, so '9' never appears in the ID. 
I realise I missed the fact that there should be a space-separated list of cell IDs, so still working on the best regex.

**Comment by dr-shorthair** [comment]
([N-S][0-8]+)( ([N-S][0-8]+))* 

What is the motivation for breaking down the numeric parts further?

**Comment by nicholascar** [comment]
> What is the motivation for breaking down the numeric parts further?

Only me coming to understand the data! 

Is it true then that if <Feature_X> is within Cells R4 and, within that R43 that this would be listed as "R4 R43" rather than just "R43"? The more refined regex - as a specification - would make clearer what "R43" is telling me. If indeed it's single digit-per-layer then the splitting regex would be as you have it revised but perhaps (ABNF):

```
rheal-digit  = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" 
rheal-letter = "N" | "O" | "P" | "Q" | "R" |  "S" 
cell         = rheal-letter *rheal-digit
geometry     = 1*(cell SP)
```

**Comment by dr-shorthair** [comment]
I'm not sure I want to get into how the list of identifiers should be assembled & processed, yet. 
@jyucsiro and @jevy-wangfei are working on the API so they will have more insight. 
But logically 
- if the operation is `within` then R45678 &Implies; ( R4567, R456, R45, R4 ). 
- if the operation is `contains` then R45678 &Implies; ( R456780 , R456781 , R456782 , R456783 , R456784 , R456785 , R456786 , R456787 , R456788 ) !
- if the operation is `hasGeometry (level=6)` then I'm not sure what ( R456780 , R456781 ) implies ...

**Comment by bellie888** [comment]
@dr-shorthair 
Is the encoding of DGGS cells in the form 'R7430550' unique and standardized?
@bellie888 ?
Yes
four main regions around the equator, and North cap and South cap regions, no two cells will have the same ID

**Comment by dr-shorthair** [comment]
Thanks @bellie888 - I also discussed this with Byron Cochrane today. He point me to Uber's H3 and I also tracked down OpenEAGGR, which are evaluated in this paper https://pdfs.semanticscholar.org/01b6/ae26c8f5456a4f7c3c23ec96d0aa76809a18.pdf 

AFAICT rHealPIX is the only scheme with a text-based naming system - is that your understanding?

**Comment by bellie888** [comment]
@dr-shorthair 
I haven't compared rHealPIX with others.
Cheers
Joe
