### ISSUE TITLE
Bounding Box

### ISSUE THREAD

**Issue by dr-shorthair** [CSIRO-enviro-informatics/geosparql-ext-ont#9]
A very common requirement arising from spatial indexing and discovery systems is for a representation of a 'bounding box' defined by edges or faces aligned with the axes of the spatial reference system. It can be defined by the min/max limits in all the dimensions, or in a simpler form by the position of the lower-left and upper-right corners (which also works in 3-D). 

GML included `gml:Envelope` but this was not carried over into GeoSPARQL. 
There is nothing in Simple Features. So encoding a Bounding Box in GeoSPARQL requires use of a degenerate POLYGON or POLYHEDRAL SURFACE. 

Much simpler and much more functional to add an explicit BBox class with two properties for lowerLeft and upperRIght.

**Comment by situx** [comment]
I do not find it now, but I have seen implementations of WKT (EWKT?) which support an ENVELOPE as a simple feature. Maybe we should support this as well?

**Comment by dr-shorthair** [comment]
Yes, this is the same as Envelope which is defined in ISO 19107. However, there is no standard way to encode an ENVELOPE in WKT - see clause 7.2.2 in http://portal.opengeospatial.org/files/?artifact_id=25355 for the BNF for WKT. That's why I am proposing it here for GEOX.
